/**
 * @miu2d/types - 共享类型定义
 *
 * 此包包含前后端共享的 Zod Schema 和 TypeScript 类型。
 */

export type {
  AuthOutput,
  ChangeEmailInput,
  ChangePasswordInput,
  LoginInput,
  LogoutOutput,
  RegisterInput,
  TokenInput,
} from "./auth.js";
// 认证类型
export {
  AuthOutputSchema,
  ChangeEmailInputSchema,
  ChangePasswordInputSchema,
  LoginInputSchema,
  LogoutOutputSchema,
  RegisterInputSchema,
  TokenInputSchema,
} from "./auth.js";
export type {
  IdResponse,
  Language,
  MessageResponse,
  SuccessResponse,
} from "./common.js";
// 通用类型
export {
  IdResponseSchema,
  LanguageSchema,
  MessageResponseSchema,
  normalizeLanguage,
  SuccessResponseSchema,
} from "./common.js";
export type {
  BatchConfirmUploadInput,
  BatchConfirmUploadOutput,
  BatchPrepareUploadInput,
  BatchPrepareUploadOutput,
  ConfirmUploadInput,
  CreateFolderInput,
  DeleteFileInput,
  EnsureFolderPathInput,
  EnsureFolderPathOutput,
  FileNode,
  FileType,
  GetDownloadUrlInput,
  GetDownloadUrlOutput,
  GetFilePathInput,
  GetFilePathOutput,
  GetUploadUrlInput,
  GetUploadUrlOutput,
  ListFilesInput,
  MoveFileInput,
  PathNode,
  PrepareUploadInput,
  PrepareUploadOutput,
  RenameFileInput,
} from "./file.js";
// 文件系统类型
export {
  BatchConfirmUploadInputSchema,
  BatchConfirmUploadOutputSchema,
  BatchPrepareUploadFileSchema,
  BatchPrepareUploadInputSchema,
  BatchPrepareUploadOutputSchema,
  BatchPrepareUploadResultSchema,
  ConfirmUploadInputSchema,
  CreateFolderInputSchema,
  DeleteFileInputSchema,
  EnsureFolderPathInputSchema,
  EnsureFolderPathOutputSchema,
  FileNodeSchema,
  FileTypeSchema,
  GetDownloadUrlInputSchema,
  GetDownloadUrlOutputSchema,
  GetFilePathInputSchema,
  GetFilePathOutputSchema,
  GetUploadUrlInputSchema,
  GetUploadUrlOutputSchema,
  ListFilesInputSchema,
  MoveFileInputSchema,
  PathNodeSchema,
  PrepareUploadInputSchema,
  PrepareUploadOutputSchema,
  RenameFileInputSchema,
} from "./file.js";
export type {
  CreateGameInput,
  DeleteGameInput,
  Game,
  UpdateGameInput,
} from "./game.js";
export {
  CreateGameInputSchema,
  DeleteGameInputSchema,
  GameSchema,
  UpdateGameInputSchema,
} from "./game.js";
export type {
  BossLevelBonus,
  DropConfig,
  DropProbability,
  DrugDropTier,
  EquipDropTier,
  GameConfig,
  GameConfigData,
  GameConfigDataFull,
  GetGameConfigInput,
  MagicExpConfig,
  MagicExpLevelEntry,
  MoneyDropTier,
  PlayerCombat,
  PlayerConfig,
  PlayerInitialStats,
  PlayerRestore,
  PlayerSpeed,
  PlayerThewCost,
  UpdateGameConfigInput,
} from "./gameConfig.js";
// 游戏全局配置类型
export {
  BossLevelBonusSchema,
  createDefaultDropConfig,
  createDefaultGameConfig,
  createDefaultMagicExpConfig,
  createDefaultPlayerConfig,
  DropConfigSchema,
  DropProbabilitySchema,
  DrugDropTierSchema,
  EquipDropTierSchema,
  GameConfigDataSchema,
  GameConfigSchema,
  GetGameConfigInputSchema,
  MagicExpConfigSchema,
  MagicExpLevelEntrySchema,
  MoneyDropTierSchema,
  mergeGameConfig,
  PlayerCombatSchema,
  PlayerConfigSchema,
  PlayerInitialStatsSchema,
  PlayerRestoreSchema,
  PlayerSpeedSchema,
  PlayerThewCostSchema,
  UpdateGameConfigInputSchema,
} from "./gameConfig.js";
export type {
  BatchImportGoodInput,
  BatchImportGoodItem,
  BatchImportGoodResult,
  CreateGoodInput,
  DeleteGoodInput,
  DrugData,
  EquipmentData,
  EquipPosition,
  EventData,
  GetGoodInput,
  Good,
  GoodEffectType,
  GoodKind,
  GoodListItem,
  ImportGoodInput,
  ListGoodInput,
  UpdateGoodInput,
} from "./good.js";
// 物品类型
export {
  BatchImportGoodInputSchema,
  BatchImportGoodItemSchema,
  BatchImportGoodResultSchema,
  CreateGoodInputSchema,
  createDefaultGood,
  DeleteGoodInputSchema,
  DrugDataSchema,
  EquipmentDataSchema,
  EquipPositionEnum,
  EquipPositionFromValue,
  EquipPositionLabels,
  EquipPositionValues,
  EventDataSchema,
  GetGoodInputSchema,
  GoodEffectTypeEnum,
  GoodEffectTypeLabels,
  GoodKindEnum,
  GoodKindFromValue,
  GoodKindLabels,
  GoodKindValues,
  GoodListItemSchema,
  GoodSchema,
  getActualEffectType,
  getEffectTypeOptions,
  getVisibleFieldsByKind,
  ImportGoodInputSchema,
  ListGoodInputSchema,
  UpdateGoodInputSchema,
} from "./good.js";
export type {
  CreateLevelConfigInput,
  DeleteLevelConfigInput,
  GetLevelConfigInput,
  ImportLevelConfigInput,
  LevelConfig,
  LevelConfigListItem,
  LevelDetail,
  LevelUserType,
  ListLevelConfigInput,
  UpdateLevelConfigInput,
} from "./level.js";
// 等级配置类型
export {
  CreateLevelConfigInputSchema,
  createDefaultLevelConfig,
  createDefaultLevelDetail,
  createDefaultLevels as createDefaultLevelConfigLevels,
  DeleteLevelConfigInputSchema,
  GetLevelConfigInputSchema,
  ImportLevelConfigInputSchema,
  LevelConfigListItemSchema,
  LevelConfigSchema,
  LevelDetailSchema,
  LevelUserTypeEnum,
  ListLevelConfigInputSchema,
  UpdateLevelConfigInputSchema,
} from "./level.js";
export type {
  AttackFile,
  BatchImportMagicInput,
  BatchImportMagicItem,
  BatchImportMagicResult,
  CreateMagicInput,
  DeleteMagicInput,
  GetMagicInput,
  ImportMagicInput,
  ListMagicInput,
  Magic,
  MagicBase,
  MagicBelong,
  MagicLevel,
  MagicListItem,
  MagicMoveKind,
  MagicRegionType,
  MagicSpecialKind,
  MagicUserType,
  UpdateMagicInput,
} from "./magic.js";
// 武功类型
export {
  AttackFileSchema,
  BatchImportMagicInputSchema,
  BatchImportMagicItemSchema,
  BatchImportMagicResultSchema,
  CreateMagicInputSchema,
  createDefaultAttackFile,
  createDefaultLevels,
  createDefaultMagic,
  DeleteMagicInputSchema,
  GetMagicInputSchema,
  getVisibleFieldsByMoveKind,
  ImportMagicInputSchema,
  ListMagicInputSchema,
  MagicBaseSchema,
  MagicBelongEnum,
  MagicBelongFromValue,
  MagicBelongLabels,
  MagicBelongValues,
  MagicLevelSchema,
  MagicListItemSchema,
  MagicMoveKindEnum,
  MagicMoveKindFromValue,
  MagicMoveKindLabels,
  MagicMoveKindValues,
  MagicRegionTypeEnum,
  MagicRegionTypeFromValue,
  MagicRegionTypeLabels,
  MagicRegionTypeValues,
  MagicSchema,
  MagicSpecialKindEnum,
  MagicSpecialKindFromValue,
  MagicSpecialKindLabels,
  MagicSpecialKindValues,
  MagicUserTypeEnum,
  UpdateMagicInputSchema,
} from "./magic.js";
export type {
  BatchImportNpcInput,
  BatchImportNpcResult,
  CreateNpcInput,
  CreateNpcResInput,
  DeleteNpcInput,
  DeleteNpcResInput,
  GetNpcInput,
  GetNpcResInput,
  ImportNpcInput,
  ImportNpcItem,
  ListNpcInput,
  ListNpcResInput,
  Npc,
  NpcBase,
  NpcKind,
  NpcListItem,
  NpcRelation,
  NpcRes,
  NpcResListItem,
  NpcResource,
  NpcState,
  NpcStateResource,
  UpdateNpcInput,
  UpdateNpcResInput,
} from "./npc.js";
// NPC 类型
export {
  BatchImportNpcInputSchema,
  BatchImportNpcResultSchema,
  CreateNpcInputSchema,
  CreateNpcResInputSchema,
  createDefaultNpc,
  createDefaultNpcResource,
  DeleteNpcInputSchema,
  DeleteNpcResInputSchema,
  GetNpcInputSchema,
  GetNpcResInputSchema,
  getNpcImageCandidates,
  getVisibleFieldsByNpcKind,
  ImportNpcInputSchema,
  ImportNpcItemSchema,
  ListNpcInputSchema,
  ListNpcResInputSchema,
  NpcBaseSchema,
  NpcKindEnum,
  NpcKindFromValue,
  NpcKindLabels,
  NpcKindValues,
  NpcListItemSchema,
  NpcRelationEnum,
  NpcRelationFromValue,
  NpcRelationLabels,
  NpcRelationValues,
  NpcResListItemSchema,
  // 资源路径规范化
  NpcResourcePaths,
  NpcResourceSchema,
  NpcResSchema,
  NpcSchema,
  NpcStateEnum,
  NpcStateLabels,
  NpcStateResourceSchema,
  normalizeNpcImagePath,
  normalizeNpcResourcePaths,
  normalizeNpcSoundPath,
  npcStateToResourceKey,
  UpdateNpcInputSchema,
  UpdateNpcResInputSchema,
} from "./npc.js";
export type {
  BatchImportObjInput,
  BatchImportObjResult,
  CreateObjInput,
  CreateObjResInput,
  DeleteObjInput,
  DeleteObjResInput,
  GetObjInput,
  GetObjResInput,
  ImportObjInput,
  ImportObjItem,
  ListObjInput,
  ListObjResInput,
  Obj,
  ObjBase,
  ObjKind,
  ObjListItem,
  ObjRes,
  ObjResListItem,
  ObjResource,
  ObjState,
  ObjStateResource,
  UpdateObjInput,
  UpdateObjResInput,
} from "./obj.js";
// Object 类型
export {
  BatchImportObjInputSchema,
  BatchImportObjResultSchema,
  CreateObjInputSchema,
  CreateObjResInputSchema,
  createDefaultObj,
  createDefaultObjRes,
  createDefaultObjResource,
  DeleteObjInputSchema,
  DeleteObjResInputSchema,
  GetObjInputSchema,
  GetObjResInputSchema,
  getVisibleFieldsByObjKind,
  ImportObjInputSchema,
  // 导入
  ImportObjItemSchema,
  ListObjInputSchema,
  // Object 资源 API
  ListObjResInputSchema,
  normalizeObjImagePath,
  normalizeObjResourcePaths,
  normalizeObjSoundPath,
  ObjBaseSchema,
  ObjKindEnum,
  ObjKindFromValue,
  ObjKindLabels,
  ObjKindValues,
  ObjListItemSchema,
  ObjResListItemSchema,
  // 资源路径规范化
  ObjResourcePaths,
  ObjResourceSchema,
  ObjResSchema,
  ObjSchema,
  ObjStateEnum,
  ObjStateLabels,
  ObjStateResourceSchema,
  UpdateObjInputSchema,
  UpdateObjResInputSchema,
} from "./obj.js";
export type {
  BatchImportPlayerInput,
  BatchImportPlayerResult,
  CreatePlayerInput,
  DeletePlayerInput,
  GetPlayerInput,
  ImportPlayerInput,
  ListPlayerInput,
  Player,
  PlayerBase,
  PlayerInitialGood,
  PlayerInitialMagic,
  PlayerListItem,
  UpdatePlayerInput,
} from "./player.js";
// 玩家角色类型
export {
  BatchImportPlayerInputSchema,
  BatchImportPlayerItemSchema,
  BatchImportPlayerResultSchema,
  CreatePlayerInputSchema,
  createDefaultPlayer,
  DeletePlayerInputSchema,
  GetPlayerInputSchema,
  ImportPlayerInputSchema,
  ListPlayerInputSchema,
  PlayerBaseSchema,
  PlayerInitialGoodSchema,
  PlayerInitialMagicSchema,
  PlayerListItemSchema,
  PlayerSchema,
  UpdatePlayerInputSchema,
} from "./player.js";
export type {
  AdminCreateSaveInput,
  AdminDeleteSaveInput,
  AdminListSavesInput,
  AdminListSavesOutput,
  AdminUpdateSaveInput,
  DeleteSaveInput,
  GetSaveInput,
  GetSharedSaveInput,
  ListSavesInput,
  SaveDataResponse,
  SaveSlot,
  ShareSaveInput,
  UpsertSaveInput,
} from "./save.js";
// 存档类型
export {
  AdminCreateSaveInputSchema,
  AdminDeleteSaveInputSchema,
  AdminListSavesInputSchema,
  AdminListSavesOutputSchema,
  AdminUpdateSaveInputSchema,
  DeleteSaveInputSchema,
  GetSaveInputSchema,
  GetSharedSaveInputSchema,
  ListSavesInputSchema,
  SaveDataResponseSchema,
  SaveSlotSchema,
  ShareSaveInputSchema,
  UpsertSaveInputSchema,
} from "./save.js";
export type {
  ClearAllScenesInput,
  ClearAllScenesResult,
  CreateSceneInput,
  DeleteSceneInput,
  GetSceneInput,
  ImportSceneBatchInput,
  ImportSceneBatchResult,
  ImportSceneItem,
  ListSceneInput,
  MiuMapDataDto,
  MsfEntryDto,
  Scene,
  SceneData,
  SceneItemKind,
  SceneListItem,
  SceneNpcData,
  SceneNpcEntry,
  SceneObjData,
  SceneObjEntry,
  TrapEntryDto,
  UpdateSceneInput,
} from "./scene.js";
// 场景类型
export {
  ClearAllScenesInputSchema,
  ClearAllScenesResultSchema,
  CreateSceneInputSchema,
  classifySaveFile,
  classifyScriptFile,
  DeleteSceneInputSchema,
  extractDisplayName,
  GetSceneInputSchema,
  getSceneDataCounts,
  ImportSceneBatchInputSchema,
  ImportSceneBatchResultSchema,
  ImportSceneItemSchema,
  ListSceneInputSchema,
  MiuMapDataDtoSchema,
  parseIniContent,
  parseMapFileName,
  parseNpcEntries,
  parseObjEntries,
  SceneItemKindEnum,
  SceneItemKindLabels,
  SceneListItemSchema,
  SceneSchema,
  UpdateSceneInputSchema,
} from "./scene.js";
export type {
  BatchImportShopInput,
  BatchImportShopItem,
  BatchImportShopResult,
  CreateShopInput,
  DeleteShopInput,
  GetShopInput,
  ImportShopInput,
  ListShopInput,
  Shop,
  ShopItem,
  ShopListItem,
  UpdateShopInput,
} from "./shop.js";
// 商店类型
export {
  BatchImportShopInputSchema,
  BatchImportShopItemSchema,
  BatchImportShopResultSchema,
  CreateShopInputSchema,
  createDefaultShop,
  DeleteShopInputSchema,
  GetShopInputSchema,
  ImportShopInputSchema,
  ListShopInputSchema,
  ShopItemSchema,
  ShopListItemSchema,
  ShopSchema,
  UpdateShopInputSchema,
} from "./shop.js";
export type {
  CreateTalkEntryInput,
  DeleteTalkEntryInput,
  GetTalkDataInput,
  ImportTalkDataInput,
  SearchTalkInput,
  SearchTalkResult,
  TalkData,
  TalkDataResult,
  TalkEntry,
  UpdateTalkDataInput,
  UpdateTalkEntryInput,
} from "./talk.js";
// --- talk ---
export {
  CreateTalkEntryInputSchema,
  DeleteTalkEntryInputSchema,
  exportTalkIndexTxt,
  extractSpeakerName,
  GetTalkDataInputSchema,
  ImportTalkDataInputSchema,
  parseTalkIndexTxt,
  SearchTalkInputSchema,
  SearchTalkResultSchema,
  TalkDataResultSchema,
  TalkDataSchema,
  TalkEntrySchema,
  UpdateTalkDataInputSchema,
  UpdateTalkEntryInputSchema,
} from "./talk.js";
export type {
  GetPortraitMapInput,
  ImportPortraitMapInput,
  PortraitEntry,
  PortraitMap,
  PortraitMapResult,
  UpdatePortraitMapInput,
} from "./talkPortrait.js";
// 对话头像映射类型
export {
  exportPortraitIni,
  GetPortraitMapInputSchema,
  ImportPortraitMapInputSchema,
  PortraitEntrySchema,
  PortraitMapResultSchema,
  PortraitMapSchema,
  parsePortraitIni,
  UpdatePortraitMapInputSchema,
} from "./talkPortrait.js";
export type { User, UserSettings, UserUpdateInput } from "./user.js";
// 用户类型
export {
  UserSchema,
  UserSettingsPatchSchema,
  UserSettingsSchema,
  UserUpdateInputSchema,
} from "./user.js";
